server:
  port: 8081

spring:
  profiles:
    active: core,discovery-nacos,loadbalancer,openfeign
  application:
    name: @project.artifactId@


#nacos-config的值会覆盖项目中application文件的值
my:
  nickName: 小石头1
  nacos:
    name: 李硕